input {
  beats {
    port => 5044 # Принимаем данные от Filebeat
  }
}

filter {
  # Так как приложение пишет в stdout JSON, Docker сохраняет его как строку в поле 'message'.
  # Распаковываем эту строку обратно в полноценные JSON-поля.
  json {
    source => "message"
    target => "go" # Все поля вашего приложения (level, msg, request_id) уйдут в объект "go"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "go-app-filebeat-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}